[package]
name = "skylink"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "skylink-cli"
path = "src/bin/main.rs"

[dependencies]
postcard = "1.1.1"
heapless = "0.7"
serde = { version = "1", default-features = false }
